### ISSUE TITLE
deploy-website action doesn't work

### ISSUE THREAD

**Issue by wench** [exult/exult-web#9]
The deploy-website action doesn't work. It fails with Authentication failures.

**Comment by DominusExult** [comment]
I've run the update.sh "manually" now.

Looked a bit into it and the scp command https://github.com/exult/exult-web/blob/master/.github/workflows/deploy-website.yml#L29 works, the zip is indeed copied over to the SF server. So the `"${{ secrets.SSH_PRIVATE_KEY }}"` works.
When I try to use the SF shell with my ages old ssh keys I get asked for my password which looks similar to this issue on SF https://sourceforge.net/p/forge/site-support/25134/.
Now I don't know if I'm running into the same issue or my key is just too old. Right now I have to do something else before reading up on what I need to do to get the correct keys.
The issue could also be that we need a delay between creating the shell and issuing the commands to the shell.

@marzojr since this was your rsa keys, does creating a shell work for you without having to enter the password?

**Comment by marzojr** [comment]
I regenerated the id_ed25519 keys used, made the deploy action name them id_ed25519 instead of id_rsa. I also added some retry logic to the SSH connections, as key authentication seems to be sporadically failing in SF.net. It seems to be working well enough now.

Feel free to reopen if it starts to fail again.

**Comment by DominusExult** [comment]
Thank you @marzojr

**Comment by DominusExult** [comment]
@marzojr now the snapshot release is failing with
```
Received disconnect from 216.105.38.21 port 22:2: Too many authentication failures
Disconnected from 216.105.38.21 port 22
lost connection
```
https://github.com/exult/exult/actions/runs/7317996468/job/19934706825#step:9:12

**Comment by marzojr** [comment]
I updated the Exult repo the same way. It should work now.
